# ---

services:
  postgres:
    image: postgres:18.1-alpine
    container_name: ${PROJECT_NAME}_postgres
    environment:
      POSTGRES_DB: ${PROJECT_NAME}_local
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: localpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  redis:
    image: redis:8.4.0-alpine
    container_name: ${PROJECT_NAME}_redis
    command: >
      --requirepass localpass
    ports:
      - "6300:6379"
    tmpfs:
      - /data

volumes:
  postgres-data:
    driver: local
    name: ${PROJECT_NAME}_postgres
